---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: rhte2023-gitops-clusters-location
  namespace: openshift-gitops
spec:
  clusterSets:
    - rhte2023-gitops-clusters
  predicates:
    - requiredClusterSelector:
        claimSelector:
          matchExpressions:
            - key: region.open-cluster-management.io
              operator: In
              values:
                - eu-west-1
        labelSelector:
          matchLabels:
            area: fringe
