---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: rhte2023-gitops-clusters-cpu
  namespace: openshift-gitops
spec:
  clusterSets:
    - rhte2023-gitops-clusters
  numberOfClusters: 1
  prioritizerPolicy:
    configurations:
      - scoreCoordinate:
          type: BuiltIn
          builtIn: 
            ResourceAllocatableCPU
        weight: -9
      - scoreCoordinate:
          type: BuiltIn
          builtIn: 
            ResourceAllocatableMemory
        weight: -9
