apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhte2023-application-03
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: rhte2023-gitops-clusters-location
        requeueAfterSeconds: 180
  template:
    metadata:
      name: rhte2023-application-03-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/jclaret/rhte-2023-acm-apps.git
        targetRevision: main
        path: rhte2023/04_deploy_applications/rhte2023-application-03
      destination:
        namespace: rhte2023-application-03
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
